version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend_app
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=tienda
    restart: always

  db:
    build: ./backend/db
    container_name: backend_db
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=tienda
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

volumes:
  db_data:
